// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/loading": {
    params: {};
  };
  "/homePage": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/api/login": {
    params: {};
  };
  "/api/user-activity": {
    params: {};
  };
  "/api/user": {
    params: {};
  };
  "/api/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/loading" | "/homePage" | "/dashboard" | "/*" | "/api/login" | "/api/user-activity" | "/api/user" | "/api/logout";
  };
  "./pages/Login.tsx": {
    id: "pages/Login";
    page: "/";
  } | {
    id: "login-page";
    page: "/login";
  };
  "./pages/Loading.jsx": {
    id: "pages/Loading";
    page: "/loading";
  };
  "./pages/HomePage.jsx": {
    id: "pages/HomePage";
    page: "/homePage";
  };
  "./pages/Dashboard.jsx": {
    id: "pages/Dashboard";
    page: "/dashboard";
  };
  "./pages/Error404.jsx": {
    id: "pages/Error404";
    page: "/*";
  };
  "./routes/api.login.jsx": {
    id: "routes/api.login";
    page: "/api/login";
  };
  "./routes/api.user-activity.jsx": {
    id: "routes/api.user-activity";
    page: "/api/user-activity";
  };
  "./routes/api.user-info.jsx": {
    id: "routes/api.user-info";
    page: "/api/user";
  };
  "./routes/api.logout.jsx": {
    id: "routes/api.logout";
    page: "/api/logout";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/Login": typeof import("./src/./pages/Login.tsx");
  "login-page": typeof import("./src/./pages/Login.tsx");
  "pages/Loading": typeof import("./src/./pages/Loading.jsx");
  "pages/HomePage": typeof import("./src/./pages/HomePage.jsx");
  "pages/Dashboard": typeof import("./src/./pages/Dashboard.jsx");
  "pages/Error404": typeof import("./src/./pages/Error404.jsx");
  "routes/api.login": typeof import("./src/./routes/api.login.jsx");
  "routes/api.user-activity": typeof import("./src/./routes/api.user-activity.jsx");
  "routes/api.user-info": typeof import("./src/./routes/api.user-info.jsx");
  "routes/api.logout": typeof import("./src/./routes/api.logout.jsx");
};